# Generated by Django 2.0.7 on 2019-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('phone_source', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_destination', models.CharField(blank=True, max_length=11, null=True)),
                ('record_type', models.CharField(choices=[('start', 'start'), ('end', 'end')], default=1, max_length=5)),
                ('record_timestamp', models.DateTimeField()),
            ],
        ),
    ]
