# Generated by Django 2.0.7 on 2018-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_type',
            field=models.CharField(choices=[(1, 'start'), (2, 'end')], default=1, max_length=5),
        ),
    ]
