# Generated by Django 2.0.7 on 2018-07-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_records', '0002_auto_20180710_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_type.RecordType'),
        ),
    ]
