# Generated by Django 2.0.7 on 2018-07-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_records', '0003_auto_20180710_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='record_type.RecordType'),
        ),
    ]
