# Generated by Django 2.0.7 on 2018-07-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_records', '0004_auto_20180710_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_type',
            field=models.CharField(choices=[(1, 'start'), (2, 'end')], default=1, max_length=5),
        ),
    ]
