# Generated by Django 2.0.7 on 2018-07-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_records', '0005_auto_20180710_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='record_type',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end')], default=1, max_length=5),
        ),
    ]
