# Generated by Django 2.0.7 on 2018-07-16 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelephoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^((10)|([1-9][1-9]))\\d{8,9}$')])),
                ('destination', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^((10)|([1-9][1-9]))\\d{8,9}$')])),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^(10|11|12|[1-9])[-]\\d{4}$')])),
            ],
        ),
    ]
