# Generated by Django 2.0.7 on 2018-07-13 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_bill', '0003_telephonebill_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonebill',
            name='period',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^\\d{2}[-]\\d{4}$')]),
        ),
    ]
