# Generated by Django 2.0.7 on 2018-07-13 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephone_bill', '0004_auto_20180713_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonebill',
            name='period',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^(10|11|12|[0][1-9])[-]\\d{4}$')]),
        ),
    ]
